CREATE TABLE IF NOT EXISTS teams
(
    team_id bigint not null,
    name    varchar(255),
    flag    varchar(20),
    CONSTRAINT pk_teams PRIMARY KEY (team_id)
);

CREATE TABLE IF NOT EXISTS matches
(
    match_id integer not null,
    scores1  integer not null,
    scores2  integer not null,
    start    timestamp,
    team1_id    integer,
    team2_id   integer,
    CONSTRAINT pk_matches PRIMARY KEY (match_id),
    CONSTRAINT FK_TEAM1_ON_TEAMS FOREIGN KEY (team1_id) REFERENCES teams (team_id),
    CONSTRAINT FK_TEAM2_ON_TEAMS FOREIGN KEY (team2_id) REFERENCES teams (team_id)
);


CREATE TABLE IF NOT EXISTS users
(
    chat_id  bigint not null,
    username varchar(255),
    points integer,
    exact_pred integer,
    CONSTRAINT pk_user PRIMARY KEY (chat_id)
);

CREATE TABLE IF NOT EXISTS predictions
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    scores1  integer                                 not null,
    scores2  integer                                 not null,
    match_id integer
        constraint fk5gyk6l61eh61hmb9u1mr6hd7v
            references matches,
    chat_id  bigint
        constraint fkf2caevm5l6wp5enmg1vr0biq
            references users,
    points  integer,
    CONSTRAINT pk_predictions PRIMARY KEY (id),
    CONSTRAINT UQ_MATCH_USER UNIQUE (match_id, chat_id)
);

CREATE TABLE IF NOT EXISTS group_user
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id  bigint not null,
    user_id  bigint not null,
    CONSTRAINT pk_group_user PRIMARY KEY (id),
    CONSTRAINT FK_USER_ON_GROUP_USER FOREIGN KEY (user_id) REFERENCES users (chat_id) ON DELETE CASCADE
);
