CREATE TABLE IF NOT EXISTS teams
(
    team_id bigint not null
        primary key,
    name    varchar(255),
    flag    varchar(20)
);

CREATE TABLE IF NOT EXISTS matches
(
    match_id integer not null
        primary key,
    scores1  integer not null,
    scores2  integer not null,
    start    timestamp,
    team1_id    integer,
    team2_id   integer,
    CONSTRAINT FK_TEAM1_ON_TEAMS FOREIGN KEY (team1_id) REFERENCES teams (team_id),
    CONSTRAINT FK_TEAM2_ON_TEAMS FOREIGN KEY (team2_id) REFERENCES teams (team_id)
);


CREATE TABLE IF NOT EXISTS users
(
    chat_id  bigint not null
        primary key,
    username varchar(255),
    points integer,
    exact_pred integer
);

CREATE TABLE IF NOT EXISTS predictions
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    scores1  integer                                 not null,
    scores2  integer                                 not null,
    match_id integer
        constraint fk5gyk6l61eh61hmb9u1mr6hd7v
            references matches,
    chat_id  bigint
        constraint fkf2caevm5l6wp5enmg1vr0biq
            references users,
    CONSTRAINT UQ_MATCH_USER UNIQUE (match_id, chat_id)
);
